# Generated by Django 5.2.3 on 2025-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='acount_type',
            field=models.CharField(default='user', max_length=80),
        ),
    ]
