# Generated by Django 5.2.5 on 2025-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('E', 'Electornies'), ('C', 'Clothing'), ('HG', 'Home & Garden'), ('S', 'Sports'), ('B', 'Books'), ('F', 'Foods'), ('O', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
