# Generated by Django 5.2.5 on 2025-08-20 19:08

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('E', 'Electornies'), ('C', 'Clothing'), ('HG', 'Home & Garden'), ('S', 'Sports'), ('B', 'Books'), ('F', 'Foods'), ('O', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('phone', phone_field.models.PhoneField(default=2090768, max_length=31)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.item')),
            ],
        ),
    ]
