# Generated by Django 5.2.5 on 2025-08-19 10:40

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
    ]
