# Generated by Django 5.2.5 on 2025-08-19 10:43

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0003_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
