# Generated by Django 5.2.5 on 2025-08-19 11:19

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('marketapp', '0004_alter_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address1',
            field=address.models.AddressField(default='Banjul', on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AddField(
            model_name='product',
            name='address2',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
    ]
