# Generated by Django 5.2.5 on 2025-08-19 11:20

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('marketapp', '0005_product_address1_product_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address1',
            field=address.models.AddressField(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
